### ISSUE TITLE
Use a service instead of reopening Ember.Route & Ember.Router

### ISSUE THREAD

**Issue by taras** [didacte/ember-meta-meta#1]
You might want considering using a service that's injected into every route instead of reopening Ember.Route & Ember.Router. It will be more future proof and won't rely on global Ember being available (which will probably change in the future).

The API will have to change a bit, but not majorly. Your example would look like this. 

```
export default Ember.Route.extend({
  setupController: function (controller, model) {
    this.meta.setMetas({
      title: 'This Is News Title',
      description: 'This Is News Description',
      'og:image': 'https://exemple.net/latest-news.png'
    });
  }
});
```

**Comment by j15e** [comment]
I will look into this next time I work on the add on, I didn't know about the services concept. Definitively a good suggestion to avoid relying on globals!

I will check a few other addons using this concept, like this one seems to nail it properly (note to myself) : https://github.com/ride/ember-stripe-service

If you have any other nice exemple let me know
