### ISSUE TITLE
FastBoot compatibility

### ISSUE THREAD

**Issue by locks** [didacte/ember-meta-meta#8]
Hi! I'm trying to use ember-meta-meta in my application, but when I run `ember fastboot` I'm getting the following error:

```
TypeError: _emberMetalProperty_get.get(...).getURL is not a function at [object Object]. (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:37104:60) at Descriptor.ComputedPropertyPrototype.get (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:24406:28) at Object.get (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:30060:19) at [object Object]._emberApplicationSystemEngineInstance.default.extend.getURL (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:14143:38) at Result._finalizeMetadata (/Users/ricardomendes/src/poupapp/node_modules/fastboot/lib/result.js:74:25) at Result._finalize (/Users/ricardomendes/src/poupapp/node_modules/fastboot/lib/result.js:64:12) at /Users/ricardomendes/src/poupapp/node_modules/fastboot/lib/ember-app.js:225:26 at tryCatch (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:61543:14) at invokeCallback (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:61558:15) at publish (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:61526:9) at /Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:41428:7 at Queue.invokeWithOnError (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:10468:18) at Object.Queue.flush (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:10523:11) at Object.DeferredActionQueues.flush (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:10331:17) at Object.Backburner.end (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:10686:25) at Timeout._onTimeout (/Users/ricardomendes/src/poupapp/dist/fastboot/vendor.js:11252:18) at tryOnTimeout (timers.js:224:11) at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by jbourassa** [comment]
Hey @locks,

Have you looked into [ember-cli-meta-tags](https://github.com/ronco/ember-cli-meta-tags)? I think it may be better suited for fastboot.

Cheers,
Jimmy

**Comment by j15e** [comment]
I did not test compatibility with Fastboot, but I am not sure how this is related to the add-on. 

Main limitations with Fastboot are jQuery and didInsertElement events, but the add-on use none of these. 

See theses 2 issues that seems to fix the specific bug your reported, in fastboot & ember : 

https://github.com/ember-fastboot/ember-cli-fastboot/issues/223
https://github.com/ember-fastboot/fastboot/pull/71

**Comment by j15e** [comment]
Hi, update : I discussed with Jimmy and we won't fix this as it would require to completely circumvent the usage of the dom everywhere in the add-on code in case we are in a backend node js server as with Fastboot. 

Look at [ember-cli-meta-tags](https://github.com/ronco/ember-cli-meta-tags) which use [ember-cli-head](https://github.com/ronco/ember-cli-head/blob/master/app/instance-initializers/fastboot/head.js#L2-L13) which do that circumventing.

**Comment by locks** [comment]
I appreciate the feedback :) I'll try your suggestions, thank you
