### ISSUE TITLE
Fastboot compatibility

### ISSUE THREAD

**Issue by RobbieTheWagner** [didacte/ember-meta-meta#9]
Need to do safety checks for `window` and `document` to get working with fastboot. I can work on a PR later, perhaps.

**Comment by kyleshevlin** [comment]
+1. Ran into this issue today myself. Hi Robert, fancy seeing you here :).

**Comment by j15e** [comment]
Please take the time to read the previous PR regarding the same issue here : https://github.com/didacte/ember-meta-meta/issues/8

If you want to take the time to rewrite the addon to support this I'll be happy but I think you are almost certainly better off using an other addon already doing that.

**Comment by RobbieTheWagner** [comment]
Yes, I would recommend ember-cli-head. It's what I now use.
